import type { Metadata } from "next";
import "@/styles/globals.css";
import { ConvexClientProvider } from "@/providers/convex-client-provider";
import { amiri } from "@/styles/fonts";
import { Toaster } from "@/components/ui/sonner";
import { DirectionProvider } from "@/components/ui/direction";

import { ConvexAuthNextjsServerProvider } from "@convex-dev/auth/nextjs/server";
import { ThemeProvider } from "@/components/theme-provider";

export const metadata: Metadata = {
  title: "أثـر",
  description: "Generated by create next app",

  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="ar"
      dir="rtl"
      className={`${amiri.variable} ${amiri.variable} h-full antialiased`}
      suppressHydrationWarning
    >
      <body className="flex min-h-full flex-col">
        <ConvexAuthNextjsServerProvider storage="localStorage">
          <ThemeProvider
            defaultTheme="light"
            attribute="class"
            enableColorScheme
          >
            <ConvexClientProvider>
              <DirectionProvider dir="rtl" direction="rtl">
                {children}
                <Toaster />
              </DirectionProvider>
            </ConvexClientProvider>
          </ThemeProvider>
        </ConvexAuthNextjsServerProvider>
      </body>
    </html>
  );
}
